/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasosRouteImport } from './routes/casos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as MetodoRouteImport } from './routes/metodo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosRoute = CasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casos': typeof CasosRoute
  '/contacto': typeof ContactoRoute
  '/metodo': typeof MetodoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casos': typeof CasosRoute
  '/contacto': typeof ContactoRoute
  '/metodo': typeof MetodoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/casos': typeof CasosRoute
  '/contacto': typeof ContactoRoute
  '/metodo': typeof MetodoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/casos' | '/contacto' | '/metodo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/casos' | '/contacto' | '/metodo'
  id: '__root__' | '/' | '/casos' | '/contacto' | '/metodo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasosRoute: typeof CasosRoute
  ContactoRoute: typeof ContactoRoute
  MetodoRoute: typeof MetodoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos': {
      id: '/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof CasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasosRoute: CasosRoute,
  ContactoRoute: ContactoRoute,
  MetodoRoute: MetodoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
